<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DatabaseDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $this->seedUsuario(); // 2 rows
        $this->seedProveedors(); // 2 rows
        $this->seedCategoria(); // 5 rows
        $this->seedAtributo(); // 6 rows
        $this->seedProducto(); // 5 rows
        $this->seedCatalogos(); // 1 rows
        $this->seedProductoatributo(); // 8 rows
        $this->seedVariante(); // 10 rows
        $this->seedVarianteImagen(); // 27 rows
        $this->seedVariantevalor(); // 18 rows
        $this->seedCompra(); // 9 rows
        $this->seedCompraDetalle(); // 9 rows
        $this->seedMovimientoBodega(); // 12 rows
        $this->seedVenta(); // 17 rows
        $this->seedSalida(); // 17 rows
        $this->seedDetalleventa(); // 17 rows
        $this->seedComisionVendedor(); // 16 rows
        $this->resetPostgresSequences();
    }

    protected function seedUsuario(): void
    {
        $data = [
            [
                'id' => 1,
                'nombre_real' => 'Josue',
                'telefono' => NULL,
                'username' => 'steven19denoviembre@gmail.com',
                'password' => '$2y$12$/UVexgaX84x2M2/9gm0f9.gbYunnfHbHRsYYsAnImlD4f.1E4wMOy',
                'rol' => 'admin',
                'estado' => 1,
                'token' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-09-21 22:15:07',
                'updated_at' => '2026-09-21 22:57:07',
            ],
            [
                'id' => 2,
                'nombre_real' => 'Ana Plasma',
                'telefono' => '7906-5467',
                'username' => 'anaplasma@gmail.com',
                'password' => '$2y$12$PPwSX.cMz4i8d3Vj4CrIpO9YL0z5jHNXwwUV2OrVYWjJslxMr.n1K',
                'rol' => 'vendedor',
                'estado' => 1,
                'token' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-09-22 10:41:59',
                'updated_at' => '2026-09-22 10:41:59',
            ],
        ];

        DB::table('usuario')->upsert($data, ['id'], ['nombre_real', 'telefono', 'username', 'password', 'rol', 'estado', 'token', 'remember_token', 'deleted_at', 'created_at', 'updated_at']);
    }

    protected function seedProveedors(): void
    {
        $data = [
            [
                'id' => 1,
                'nombre' => 'Curacao',
                'correo' => 'curacao@gmail.com',
                'telefono' => '2878-4729',
                'direccion' => 'Avenida falsa 123',
                'deleted_at' => NULL,
                'created_at' => '2026-09-21 22:30:47',
                'updated_at' => '2026-09-21 22:30:47',
            ],
            [
                'id' => 2,
                'nombre' => 'curacao',
                'correo' => NULL,
                'telefono' => NULL,
                'direccion' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-09-23 08:54:18',
                'updated_at' => '2026-09-23 08:54:18',
            ],
        ];

        DB::table('proveedors')->upsert($data, ['id'], ['nombre', 'correo', 'telefono', 'direccion', 'deleted_at', 'created_at', 'updated_at']);
    }

    protected function seedCategoria(): void
    {
        $data = [
            [
                'id' => 1,
                'nombre' => 'Hogar',
                'descripcion' => 'Accesorios para el hogar',
                'color' => '#d946ef',
                'estado' => true,
                'icono' => 'fa-couch',
                'orden' => 1,
            ],
            [
                'id' => 2,
                'nombre' => 'AutoParte',
                'descripcion' => 'Repuesto de auto',
                'color' => '#f97316',
                'estado' => true,
                'icono' => 'fa-car',
                'orden' => 2,
            ],
            [
                'id' => 3,
                'nombre' => 'Tecnologia',
                'descripcion' => 'Productos electrónicos',
                'color' => '#10b981',
                'estado' => false,
                'icono' => 'fa-laptop',
                'orden' => 5,
            ],
            [
                'id' => 4,
                'nombre' => 'Cocina',
                'descripcion' => 'Todo para remodelar la cocina',
                'color' => '#ef4444',
                'estado' => true,
                'icono' => 'fa-utensils',
                'orden' => 3,
            ],
            [
                'id' => 5,
                'nombre' => 'Juguetes',
                'descripcion' => 'Juguetes para niños',
                'color' => '#f43f5e',
                'estado' => true,
                'icono' => 'fa-basketball',
                'orden' => 4,
            ],
        ];

        DB::table('categoria')->upsert($data, ['id'], ['nombre', 'descripcion', 'color', 'estado', 'icono', 'orden']);
    }

    protected function seedAtributo(): void
    {
        $data = [
            [
                'id' => 1,
                'nombre' => 'Medidas',
                'created_at' => '2026-09-21 22:34:23',
                'updated_at' => '2026-09-21 22:34:23',
            ],
            [
                'id' => 2,
                'nombre' => 'Lumenes',
                'created_at' => '2026-09-21 22:34:23',
                'updated_at' => '2026-09-21 22:34:23',
            ],
            [
                'id' => 3,
                'nombre' => 'Distancia',
                'created_at' => '2026-09-21 22:34:23',
                'updated_at' => '2026-09-21 22:34:23',
            ],
            [
                'id' => 4,
                'nombre' => 'Capacidad (voltios)',
                'created_at' => '2026-09-22 10:25:13',
                'updated_at' => '2026-09-22 10:25:13',
            ],
            [
                'id' => 5,
                'nombre' => 'Angulo',
                'created_at' => '2026-09-22 10:49:32',
                'updated_at' => '2026-09-22 10:49:32',
            ],
            [
                'id' => 6,
                'nombre' => 'Medida',
                'created_at' => '2026-09-23 08:56:55',
                'updated_at' => '2026-09-23 08:56:55',
            ],
        ];

        DB::table('atributo')->upsert($data, ['id'], ['nombre', 'created_at', 'updated_at']);
    }

    protected function seedProducto(): void
    {
        $data = [
            [
                'id' => 1,
                'id_categoria' => 2,
                'sku' => 'ALO-A-001',
                'nombre' => 'ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH.',
                'descripcion' => 'ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH.

PRECIO DEL PAR $19

ALOGENAS XPLORADORA PARA MOTOS Y AUTOMÓVIL🚗🏍️
✅LUZ BLANCA, Y AMARILLA. 
✅40mil lumines de potencia 
Distancia 450 metros mejor alumbrado. 
✅LO último en tecnología a pesar el tamaño q tiene maneja una intensidad de luz a gran distancia visible. 
✅Material metálico resistente, interperie. 
✅Swich de apagado 
Manejo de luz alta y baja 
✅TAMAÑO 5Cm ANCHO Y LARGO 5.5CM

ENVIOS A TODO EL PAIS',
                'comision' => '3.00',
                'marca' => 'Angel',
                'imagen_principal' => 'productos/qr7W1wJPgEFbzEoHgjRCJgWiKf3SUqwst2qYJihq.jpg',
                'estado' => 1,
                'created_at' => '2026-09-21 22:34:23',
                'updated_at' => '2026-09-23 09:05:52',
            ],
            [
                'id' => 3,
                'id_categoria' => 2,
                'sku' => 'LUC-A-001',
                'nombre' => 'LUCES WATERMELON PARA AUTOMOVIL',
                'descripcion' => 'LUCES WATERMELON PARA AUTOMOVIL 

PRECIO PAR $8

✅LUCES WATERMELON CON SISTEMA LUZ FIJA Y STROBERS LA MEJOR MANERA PARA DARLE UN DISEÑO ÚNICO.
✅️12 voltios a 24 voltios 
✅️Medida de 5cm de altura 
Ancho de 4CM 
✅️COLORES 
🔷️AZUL HIELO 
🔷️MORADO

BUSCANOS metro galerías local 3.5A tercer nivel frente a metro san salvador',
                'comision' => '2.00',
                'marca' => 'MelonWater',
                'imagen_principal' => 'productos/B3FG2ERyjZzyNBZSWmPXDBlQJiWgCV1tHfgqBAXy.jpg',
                'estado' => 1,
                'created_at' => '2026-09-22 10:23:45',
                'updated_at' => '2026-09-22 10:23:45',
            ],
            [
                'id' => 4,
                'id_categoria' => 1,
                'sku' => 'CAM-H-001',
                'nombre' => 'CAMARA FOCO Giro 360°',
                'descripcion' => 'CAMARA DE SEGURIDAD INTELIGENTE TIPO FOCO 2 CAMARAS 

Precio $24

✅ CAMARA INTELIGENTE YOOSSE PARA TU HOGAR O NEGOCIO GIRO 360° 
Camara FULL HD: Sensor de 1080p de ultima generación.
Seguimiento Automatico: Se activa automaticamente con los movimientos .
Sistema de audio: El microfono con grabadora de audio detecta todos los sonidos ambientales.
Compatibilidad: Todos los Smarphones Compatibles.
✅Se abre con aplicacion YOOSSE 
✅ Abre las dos camaras al mismo tiempo 
✅RESOLUCIÓN NOCTURNA HD. 
✅Pueden conectarse varios dispositivos ala ves. 

✅CONTAMOS CON ENVIOS TODO EL PAIS 🚗',
                'comision' => '4.00',
                'marca' => 'Jordan',
                'imagen_principal' => 'productos/mAGt1wqoh2oJHunOFmXlhFyZGLk8LR4kpPQCetQ0.jpg',
                'estado' => 1,
                'created_at' => '2026-09-22 10:49:32',
                'updated_at' => '2026-09-22 10:49:32',
            ],
            [
                'id' => 5,
                'id_categoria' => 5,
                'sku' => 'MOT-J-001',
                'nombre' => 'MOTO COLECCIÓN DEPORTIVA S1000 RR',
                'descripcion' => 'MOTO COLECCIÓN DEPORTIVA S1000 RR 

✅️MOTITO COLECCION S1000 RR DISEÑO BMW
CON SUSPENCION DE AMORTIGUACION FLEXIBLE Y LLANTAS RODABLES.
✅️Tanque metálico 
✅️Llantas de hule resistente 
✅️Base de exhibición.
✅Medida Largo 21CM
Altura 13CM
🔷️COLORES
⏺️Blanco 
⏺️Negro

ENVIOS TODO EL PAIS',
                'comision' => '3.00',
                'marca' => 'S1000 RR',
                'imagen_principal' => 'productos/TcPxauCfWnJBl8BfuuijymxQZvx9kDZYfQataxBP.jpg',
                'estado' => 1,
                'created_at' => '2026-09-22 21:50:28',
                'updated_at' => '2026-09-22 21:50:28',
            ],
            [
                'id' => 7,
                'id_categoria' => 2,
                'sku' => 'LUC-A-002',
                'nombre' => 'LUCES TRASERAS CON EFECTO 3D',
                'descripcion' => 'LUCES TRASERAS CON EFECTO 3D

✅️LUCES TRASERAS LED redondas de 4 pulgadas con diseño de efecto de túnel infinito.
✅️Luces redondas con efecto óptico 3D de profundidad tipo abismo o túnel infinito.Uso: Ideales para funciones de freno, parada, giro o posición en camiones y trailers.
✅️COLORES 
🔷️AMARILLO 
🔷️ROJO
🔷️MORADO 
🚚ENVIOS A TODO EL PAIS',
                'comision' => '3.00',
                'marca' => NULL,
                'imagen_principal' => 'productos/DWTCl2ADxJUA9eR70DPIckZ6L1Ol0e5LfFkBKKQ0.jpg',
                'estado' => 1,
                'created_at' => '2026-09-23 08:56:55',
                'updated_at' => '2026-09-23 08:56:55',
            ],
        ];

        DB::table('producto')->upsert($data, ['id'], ['id_categoria', 'sku', 'nombre', 'descripcion', 'comision', 'marca', 'imagen_principal', 'estado', 'created_at', 'updated_at']);
    }

    protected function seedCatalogos(): void
    {
        $data = [
            [
                'id' => 1,
                'tipo' => 'pdf',
                'ruta_destino' => 'catalogos_proveedores/Zh7eTlI5r1ui7u1itiY6ohz3KvIRpSY1KRshRGkG.pdf',
                'nombre_referencia' => 'Catalogo Verano 2026',
                'id_proveedor' => 1,
                'created_at' => '2026-09-21 22:31:21',
                'updated_at' => '2026-09-21 22:31:21',
            ],
        ];

        DB::table('catalogos')->upsert($data, ['id'], ['tipo', 'ruta_destino', 'nombre_referencia', 'id_proveedor', 'created_at', 'updated_at']);
    }

    protected function seedProductoatributo(): void
    {
        $data = [
            [
                'id' => 1,
                'id_producto' => 1,
                'id_atributo' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 4,
                'id_producto' => 3,
                'id_atributo' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 5,
                'id_producto' => 1,
                'id_atributo' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 6,
                'id_producto' => 1,
                'id_atributo' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 7,
                'id_producto' => 4,
                'id_atributo' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 8,
                'id_producto' => 5,
                'id_atributo' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 9,
                'id_producto' => 7,
                'id_atributo' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 10,
                'id_producto' => 7,
                'id_atributo' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ];

        DB::table('productoatributo')->upsert($data, ['id'], ['id_producto', 'id_atributo', 'created_at', 'updated_at']);
    }

    protected function seedVariante(): void
    {
        $data = [
            [
                'id' => 1,
                'id_producto' => 1,
                'estado' => 1,
                'sku' => 'VAR-LUZ-001',
                'hash_combinacion' => '20ce2348afb6724f378d959bcfc91c62',
                'nombre_variante' => 'Luz Blanca',
                'precio_venta' => '19.00',
                'comision' => '0.00',
                'stock' => 18,
                'reserva' => 30,
                'costo_promedio' => '8.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-21 22:46:57',
                'updated_at' => '2026-09-26 22:38:22',
            ],
            [
                'id' => 2,
                'id_producto' => 1,
                'estado' => 1,
                'sku' => 'VAR-LUZ-002',
                'hash_combinacion' => 'a8d8fe3f876778a4457abdc056db2cb1',
                'nombre_variante' => 'Luz Amarrilla',
                'precio_venta' => '19.80',
                'comision' => '0.00',
                'stock' => 14,
                'reserva' => 35,
                'costo_promedio' => '8.40',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-21 23:03:00',
                'updated_at' => '2026-09-26 19:41:10',
            ],
            [
                'id' => 6,
                'id_producto' => 3,
                'estado' => 1,
                'sku' => 'VAR-MOR-001',
                'hash_combinacion' => 'ed9ab28c836a3dc726f21b25fe8316c3',
                'nombre_variante' => 'Morado',
                'precio_venta' => '2.00',
                'comision' => '0.00',
                'stock' => 0,
                'reserva' => 0,
                'costo_promedio' => '0.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-22 10:25:55',
                'updated_at' => '2026-09-22 10:25:55',
            ],
            [
                'id' => 7,
                'id_producto' => 3,
                'estado' => 1,
                'sku' => 'VAR-AZU-001',
                'hash_combinacion' => '2e113ea850bb3db498aa5d5734f88057',
                'nombre_variante' => 'Azul',
                'precio_venta' => '2.00',
                'comision' => '0.00',
                'stock' => 0,
                'reserva' => 0,
                'costo_promedio' => '0.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-22 10:26:14',
                'updated_at' => '2026-09-22 10:26:14',
            ],
            [
                'id' => 9,
                'id_producto' => 1,
                'estado' => 1,
                'sku' => 'VAR-COM-001',
                'hash_combinacion' => '58c763ecab2290f0aecd0f2eb7803ae3',
                'nombre_variante' => 'Combinada',
                'precio_venta' => '29.67',
                'comision' => '0.00',
                'stock' => 0,
                'reserva' => 30,
                'costo_promedio' => '13.33',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-22 10:35:20',
                'updated_at' => '2026-09-22 10:37:49',
            ],
            [
                'id' => 10,
                'id_producto' => 4,
                'estado' => 1,
                'sku' => 'VAR-DOS-001',
                'hash_combinacion' => '771d042fd96cad260f7cc956f4e98775',
                'nombre_variante' => 'Dos focos',
                'precio_venta' => '24.00',
                'comision' => '0.00',
                'stock' => 0,
                'reserva' => 20,
                'costo_promedio' => '10.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-22 10:50:12',
                'updated_at' => '2026-09-22 10:51:54',
            ],
            [
                'id' => 11,
                'id_producto' => 5,
                'estado' => 1,
                'sku' => 'VAR-BLA-001',
                'hash_combinacion' => 'ed9dfc2a1a8f933e91f0d47f3e555db7',
                'nombre_variante' => 'Blanca',
                'precio_venta' => '17.00',
                'comision' => '0.00',
                'stock' => 0,
                'reserva' => 30,
                'costo_promedio' => '7.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-22 21:52:58',
                'updated_at' => '2026-09-22 22:05:39',
            ],
            [
                'id' => 12,
                'id_producto' => 5,
                'estado' => 0,
                'sku' => 'VAR-NEG-001',
                'hash_combinacion' => 'b68892266432161695f27329aa80820d',
                'nombre_variante' => 'Negro',
                'precio_venta' => '3.00',
                'comision' => '0.00',
                'stock' => 0,
                'reserva' => 0,
                'costo_promedio' => '0.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-22 21:54:10',
                'updated_at' => '2026-09-22 22:13:20',
            ],
            [
                'id' => 13,
                'id_producto' => 7,
                'estado' => 1,
                'sku' => 'VAR-ROJ-001',
                'hash_combinacion' => '8e92fb699b5c06058f9ae7993baaa1cf',
                'nombre_variante' => 'Roja',
                'precio_venta' => '3.00',
                'comision' => '0.00',
                'stock' => 0,
                'reserva' => 0,
                'costo_promedio' => '0.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-23 09:01:27',
                'updated_at' => '2026-09-23 09:01:27',
            ],
            [
                'id' => 14,
                'id_producto' => 7,
                'estado' => 1,
                'sku' => 'VAR-AMA-001',
                'hash_combinacion' => '0904d1201bc211e624b1878ec55425df',
                'nombre_variante' => 'Amarilla',
                'precio_venta' => '63.00',
                'comision' => '0.00',
                'stock' => 12,
                'reserva' => 7,
                'costo_promedio' => '30.00',
                'porcentaje_ganancia' => '100.00',
                'imagen' => '',
                'created_at' => '2026-09-23 09:02:13',
                'updated_at' => '2026-09-27 14:03:45',
            ],
        ];

        DB::table('variante')->upsert($data, ['id'], ['id_producto', 'estado', 'sku', 'hash_combinacion', 'nombre_variante', 'precio_venta', 'comision', 'stock', 'reserva', 'costo_promedio', 'porcentaje_ganancia', 'imagen', 'created_at', 'updated_at']);
    }

    protected function seedVarianteImagen(): void
    {
        $data = [
            [
                'id' => 4,
                'id_variante' => 2,
                'ruta_imagen' => 'variantes/B0XPX3OmBoDeb2Tmc9xZHCsVbYQqCuDuQiH6PAqo.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-21 23:03:00',
                'updated_at' => '2026-09-21 23:03:00',
            ],
            [
                'id' => 5,
                'id_variante' => 2,
                'ruta_imagen' => 'variantes/J9VPyl8EqJpRHuBWzouXDWHipdI9CeycZiq3VK4j.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-21 23:03:00',
                'updated_at' => '2026-09-21 23:03:00',
            ],
            [
                'id' => 6,
                'id_variante' => 2,
                'ruta_imagen' => 'variantes/bYL9LiUUVsZ6k6VFicTkycvDizZqTjW2SwIOjupJ.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-21 23:03:00',
                'updated_at' => '2026-09-21 23:03:00',
            ],
            [
                'id' => 13,
                'id_variante' => 6,
                'ruta_imagen' => 'variantes/qZfX5vlZBrZ3aONdweSeRbt7cntcHKcviUtgbYwS.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-22 10:25:55',
                'updated_at' => '2026-09-22 10:25:55',
            ],
            [
                'id' => 14,
                'id_variante' => 6,
                'ruta_imagen' => 'variantes/7hQNcdOsvwIWEgqBtRMWHBU5ouTevoboptOakvtl.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 10:25:55',
                'updated_at' => '2026-09-22 10:25:55',
            ],
            [
                'id' => 15,
                'id_variante' => 7,
                'ruta_imagen' => 'variantes/TUX2vD6XRSS4Dg1GICPnvaJCdUig7YwUv0FtVRE2.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-22 10:26:14',
                'updated_at' => '2026-09-22 10:26:14',
            ],
            [
                'id' => 16,
                'id_variante' => 7,
                'ruta_imagen' => 'variantes/FuCwRANQhKGeSvbOHBwiT8xm1ROkz3AvJu7NbWeT.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 10:26:14',
                'updated_at' => '2026-09-22 10:26:14',
            ],
            [
                'id' => 17,
                'id_variante' => 1,
                'ruta_imagen' => 'variantes/kNO3nARwL64Ra6SHy1vkjbewgs9OqFpil4c1RZaE.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-22 10:28:21',
                'updated_at' => '2026-09-22 10:34:56',
            ],
            [
                'id' => 18,
                'id_variante' => 1,
                'ruta_imagen' => 'variantes/5nO4xKefOrvrSTqXs2WhPFWyHFF4Ef6glZOSo7ij.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 10:28:21',
                'updated_at' => '2026-09-22 10:34:56',
            ],
            [
                'id' => 19,
                'id_variante' => 1,
                'ruta_imagen' => 'variantes/jm6ZtVARt4EjSI1JzZjswDrZom3o91syFnAKvFc7.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 10:28:21',
                'updated_at' => '2026-09-22 10:34:56',
            ],
            [
                'id' => 22,
                'id_variante' => 9,
                'ruta_imagen' => 'variantes/H8Jhjjf6mrW2ICNLo6XwaO5IyyZCpbmFXgvjlJVo.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-22 10:35:20',
                'updated_at' => '2026-09-22 10:35:20',
            ],
            [
                'id' => 23,
                'id_variante' => 9,
                'ruta_imagen' => 'variantes/6MomgLr6PSXfaGx0iGvjVdrEA7xrTziTLbBtOODv.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 10:35:20',
                'updated_at' => '2026-09-22 10:35:20',
            ],
            [
                'id' => 24,
                'id_variante' => 10,
                'ruta_imagen' => 'variantes/uqMHIzKVohoNXcwANgOawa55Ie64mxL05uIMenug.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-22 10:50:12',
                'updated_at' => '2026-09-22 10:50:12',
            ],
            [
                'id' => 25,
                'id_variante' => 10,
                'ruta_imagen' => 'variantes/vj1MtouiOVdTRq7Yb7KXQrzzoEactKT5YQ1IWK6Z.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 10:50:13',
                'updated_at' => '2026-09-22 10:50:13',
            ],
            [
                'id' => 26,
                'id_variante' => 10,
                'ruta_imagen' => 'variantes/awEgL0L00BxJLozQ0kyjIdHDreD5Nge5sKU76Wtp.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 10:50:13',
                'updated_at' => '2026-09-22 10:50:13',
            ],
            [
                'id' => 27,
                'id_variante' => 11,
                'ruta_imagen' => 'variantes/mVoAqLNdVMfpigrBgpWsiciqLSXu1xdj1iUAF3yI.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 21:52:59',
                'updated_at' => '2026-09-22 21:52:59',
            ],
            [
                'id' => 28,
                'id_variante' => 11,
                'ruta_imagen' => 'variantes/bdDcQpNz4aZqJuPZ2sfIv10BNFl7rGFVm9nPHQf1.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-22 21:52:59',
                'updated_at' => '2026-09-22 21:52:59',
            ],
            [
                'id' => 29,
                'id_variante' => 11,
                'ruta_imagen' => 'variantes/7a0bzQJRIdw67Ey9bfBYykcdxxH3QFQdogcuHQhs.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 21:52:59',
                'updated_at' => '2026-09-22 21:52:59',
            ],
            [
                'id' => 30,
                'id_variante' => 11,
                'ruta_imagen' => 'variantes/7HxObGQdLKJG1LhdVgQxxOljCIQMBAy3sT0CTc8L.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 21:52:59',
                'updated_at' => '2026-09-22 21:52:59',
            ],
            [
                'id' => 33,
                'id_variante' => 12,
                'ruta_imagen' => 'variantes/DhQm8icwtM457l5Nz9wNuE2E2GaFUmPp0SNpeJRc.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-22 21:54:10',
                'updated_at' => '2026-09-22 21:57:00',
            ],
            [
                'id' => 34,
                'id_variante' => 12,
                'ruta_imagen' => 'variantes/e6POemxoVzka1q1TZf8P1k0LWV1xiIT3X6GJdpY1.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-22 21:54:10',
                'updated_at' => '2026-09-22 21:57:00',
            ],
            [
                'id' => 35,
                'id_variante' => 13,
                'ruta_imagen' => 'variantes/zgIekJ0Ixr2BWbG3B6WDXgMQnyG3UhbFKS8ikv4z.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-23 09:01:27',
                'updated_at' => '2026-09-23 09:01:27',
            ],
            [
                'id' => 36,
                'id_variante' => 13,
                'ruta_imagen' => 'variantes/YwQ3APGHC6M2DE1HBdofZgFM2vpTgk2l7OGIYZRq.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-23 09:01:27',
                'updated_at' => '2026-09-23 09:01:27',
            ],
            [
                'id' => 37,
                'id_variante' => 13,
                'ruta_imagen' => 'variantes/bWW9axJESMcCmVdmaxdwFnUV5FpXF9K01vFM0Z1S.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-23 09:01:27',
                'updated_at' => '2026-09-23 09:01:27',
            ],
            [
                'id' => 38,
                'id_variante' => 13,
                'ruta_imagen' => 'variantes/DFX6ECZ6C7fsW8vToSN7xp1xXaX1kQJP9Lw2AIEb.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-23 09:01:27',
                'updated_at' => '2026-09-23 09:01:27',
            ],
            [
                'id' => 39,
                'id_variante' => 14,
                'ruta_imagen' => 'variantes/fqMRa4n3TonWI5Py04BGzA3eIZMA9Nw1evwXP2tB.jpg',
                'es_principal' => 1,
                'created_at' => '2026-09-23 09:02:13',
                'updated_at' => '2026-09-23 09:02:13',
            ],
            [
                'id' => 40,
                'id_variante' => 14,
                'ruta_imagen' => 'variantes/lHjtIEriNuNPpQIouBGVJTGlAAS9aWFwyHjk6WoO.jpg',
                'es_principal' => 0,
                'created_at' => '2026-09-23 09:02:13',
                'updated_at' => '2026-09-23 09:02:13',
            ],
        ];

        DB::table('variante_imagen')->upsert($data, ['id'], ['id_variante', 'ruta_imagen', 'es_principal', 'created_at', 'updated_at']);
    }

    protected function seedVariantevalor(): void
    {
        $data = [
            [
                'id' => 19,
                'id_variante' => 2,
                'id_atributo' => 1,
                'valor' => '20cm ancho x 13 cm alto',
                'created_at' => '2026-09-21 23:03:00',
                'updated_at' => '2026-09-21 23:03:00',
            ],
            [
                'id' => 20,
                'id_variante' => 2,
                'id_atributo' => 2,
                'valor' => '40 mil',
                'created_at' => '2026-09-21 23:03:00',
                'updated_at' => '2026-09-21 23:03:00',
            ],
            [
                'id' => 21,
                'id_variante' => 2,
                'id_atributo' => 3,
                'valor' => '450 metros',
                'created_at' => '2026-09-21 23:03:00',
                'updated_at' => '2026-09-21 23:03:00',
            ],
            [
                'id' => 25,
                'id_variante' => 6,
                'id_atributo' => 4,
                'valor' => '12 a 24 volt',
                'created_at' => '2026-09-22 10:25:55',
                'updated_at' => '2026-09-22 10:25:55',
            ],
            [
                'id' => 26,
                'id_variante' => 7,
                'id_atributo' => 4,
                'valor' => '12 a 24 volt',
                'created_at' => '2026-09-22 10:26:14',
                'updated_at' => '2026-09-22 10:26:14',
            ],
            [
                'id' => 29,
                'id_variante' => 1,
                'id_atributo' => 1,
                'valor' => '20cm ancho x 13 cm alto',
                'created_at' => '2026-09-22 10:34:56',
                'updated_at' => '2026-09-22 10:34:56',
            ],
            [
                'id' => 30,
                'id_variante' => 1,
                'id_atributo' => 2,
                'valor' => '40 mil',
                'created_at' => '2026-09-22 10:34:56',
                'updated_at' => '2026-09-22 10:34:56',
            ],
            [
                'id' => 31,
                'id_variante' => 1,
                'id_atributo' => 3,
                'valor' => '450 metros',
                'created_at' => '2026-09-22 10:34:56',
                'updated_at' => '2026-09-22 10:34:56',
            ],
            [
                'id' => 32,
                'id_variante' => 9,
                'id_atributo' => 1,
                'valor' => '20cm ancho x 13 cm alto',
                'created_at' => '2026-09-22 10:35:20',
                'updated_at' => '2026-09-22 10:35:20',
            ],
            [
                'id' => 33,
                'id_variante' => 9,
                'id_atributo' => 2,
                'valor' => '40 mil',
                'created_at' => '2026-09-22 10:35:20',
                'updated_at' => '2026-09-22 10:35:20',
            ],
            [
                'id' => 34,
                'id_variante' => 9,
                'id_atributo' => 3,
                'valor' => '650 metros',
                'created_at' => '2026-09-22 10:35:20',
                'updated_at' => '2026-09-22 10:35:20',
            ],
            [
                'id' => 35,
                'id_variante' => 10,
                'id_atributo' => 5,
                'valor' => '360 °',
                'created_at' => '2026-09-22 10:50:13',
                'updated_at' => '2026-09-22 10:50:13',
            ],
            [
                'id' => 36,
                'id_variante' => 11,
                'id_atributo' => 1,
                'valor' => '21cm ancho x 13 cm alto',
                'created_at' => '2026-09-22 21:52:59',
                'updated_at' => '2026-09-22 21:52:59',
            ],
            [
                'id' => 40,
                'id_variante' => 12,
                'id_atributo' => 1,
                'valor' => '21cm ancho x 13 cm alto',
                'created_at' => '2026-09-22 21:57:00',
                'updated_at' => '2026-09-22 21:57:00',
            ],
            [
                'id' => 41,
                'id_variante' => 13,
                'id_atributo' => 2,
                'valor' => '25 mil',
                'created_at' => '2026-09-23 09:01:27',
                'updated_at' => '2026-09-23 09:01:27',
            ],
            [
                'id' => 42,
                'id_variante' => 13,
                'id_atributo' => 6,
                'valor' => '4 pulgadas',
                'created_at' => '2026-09-23 09:01:27',
                'updated_at' => '2026-09-23 09:01:27',
            ],
            [
                'id' => 43,
                'id_variante' => 14,
                'id_atributo' => 2,
                'valor' => '25 mil',
                'created_at' => '2026-09-23 09:02:13',
                'updated_at' => '2026-09-23 09:02:13',
            ],
            [
                'id' => 44,
                'id_variante' => 14,
                'id_atributo' => 6,
                'valor' => '4 pulgadas',
                'created_at' => '2026-09-23 09:02:13',
                'updated_at' => '2026-09-23 09:02:13',
            ],
        ];

        DB::table('variantevalor')->upsert($data, ['id'], ['id_variante', 'id_atributo', 'valor', 'created_at', 'updated_at']);
    }

    protected function seedCompra(): void
    {
        $data = [
            [
                'id' => 1,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-22',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '300.00',
                'total' => '300.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-21 22:47:28',
                'updated_at' => '2026-09-21 22:47:28',
            ],
            [
                'id' => 2,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-22',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '100.00',
                'total' => '100.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-21 22:47:45',
                'updated_at' => '2026-09-21 22:47:45',
            ],
            [
                'id' => 3,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-22',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '100.00',
                'total' => '100.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-21 23:03:43',
                'updated_at' => '2026-09-21 23:03:43',
            ],
            [
                'id' => 4,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-22',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '320.00',
                'total' => '320.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-21 23:03:56',
                'updated_at' => '2026-09-21 23:03:56',
            ],
            [
                'id' => 5,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-22',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '300.00',
                'total' => '300.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-22 10:36:10',
                'updated_at' => '2026-09-22 10:36:10',
            ],
            [
                'id' => 6,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-22',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '100.00',
                'total' => '100.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-22 10:37:49',
                'updated_at' => '2026-09-22 10:37:49',
            ],
            [
                'id' => 7,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-22',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '200.00',
                'total' => '200.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-22 10:51:54',
                'updated_at' => '2026-09-22 10:51:54',
            ],
            [
                'id' => 8,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-23',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '210.00',
                'total' => '210.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-22 21:54:56',
                'updated_at' => '2026-09-22 21:54:56',
            ],
            [
                'id' => 9,
                'id_proveedor' => 1,
                'id_usuario' => 1,
                'fecha_compra' => '2026-09-23',
                'referencia' => NULL,
                'observaciones' => NULL,
                'subtotal' => '660.00',
                'total' => '660.00',
                'estado' => 'recibida',
                'created_at' => '2026-09-23 09:08:47',
                'updated_at' => '2026-09-23 09:08:47',
            ],
        ];

        DB::table('compra')->upsert($data, ['id'], ['id_proveedor', 'id_usuario', 'fecha_compra', 'referencia', 'observaciones', 'subtotal', 'total', 'estado', 'created_at', 'updated_at']);
    }

    protected function seedCompraDetalle(): void
    {
        $data = [
            [
                'id' => 1,
                'id_compra' => 1,
                'id_variante' => 1,
                'cantidad' => 30,
                'precio_unitario' => '10.00',
                'subtotal' => '300.00',
                'created_at' => '2026-09-21 22:47:28',
                'updated_at' => '2026-09-21 22:47:28',
            ],
            [
                'id' => 2,
                'id_compra' => 2,
                'id_variante' => 1,
                'cantidad' => 20,
                'precio_unitario' => '5.00',
                'subtotal' => '100.00',
                'created_at' => '2026-09-21 22:47:45',
                'updated_at' => '2026-09-21 22:47:45',
            ],
            [
                'id' => 3,
                'id_compra' => 3,
                'id_variante' => 2,
                'cantidad' => 10,
                'precio_unitario' => '10.00',
                'subtotal' => '100.00',
                'created_at' => '2026-09-21 23:03:43',
                'updated_at' => '2026-09-21 23:03:43',
            ],
            [
                'id' => 4,
                'id_compra' => 4,
                'id_variante' => 2,
                'cantidad' => 40,
                'precio_unitario' => '8.00',
                'subtotal' => '320.00',
                'created_at' => '2026-09-21 23:03:56',
                'updated_at' => '2026-09-21 23:03:56',
            ],
            [
                'id' => 5,
                'id_compra' => 5,
                'id_variante' => 9,
                'cantidad' => 10,
                'precio_unitario' => '30.00',
                'subtotal' => '300.00',
                'created_at' => '2026-09-22 10:36:10',
                'updated_at' => '2026-09-22 10:36:10',
            ],
            [
                'id' => 6,
                'id_compra' => 6,
                'id_variante' => 9,
                'cantidad' => 20,
                'precio_unitario' => '5.00',
                'subtotal' => '100.00',
                'created_at' => '2026-09-22 10:37:49',
                'updated_at' => '2026-09-22 10:37:49',
            ],
            [
                'id' => 7,
                'id_compra' => 7,
                'id_variante' => 10,
                'cantidad' => 20,
                'precio_unitario' => '10.00',
                'subtotal' => '200.00',
                'created_at' => '2026-09-22 10:51:54',
                'updated_at' => '2026-09-22 10:51:54',
            ],
            [
                'id' => 8,
                'id_compra' => 8,
                'id_variante' => 11,
                'cantidad' => 30,
                'precio_unitario' => '7.00',
                'subtotal' => '210.00',
                'created_at' => '2026-09-22 21:54:56',
                'updated_at' => '2026-09-22 21:54:56',
            ],
            [
                'id' => 9,
                'id_compra' => 9,
                'id_variante' => 14,
                'cantidad' => 22,
                'precio_unitario' => '30.00',
                'subtotal' => '660.00',
                'created_at' => '2026-09-23 09:08:47',
                'updated_at' => '2026-09-23 09:08:47',
            ],
        ];

        DB::table('compra_detalle')->upsert($data, ['id'], ['id_compra', 'id_variante', 'cantidad', 'precio_unitario', 'subtotal', 'created_at', 'updated_at']);
    }

    protected function seedMovimientoBodega(): void
    {
        $data = [
            [
                'id' => 1,
                'id_variante' => 1,
                'id_compra' => 1,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 30,
                'reserva_anterior' => 0,
                'reserva_nueva' => 30,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-21 22:47:28',
                'updated_at' => '2026-09-21 22:47:28',
            ],
            [
                'id' => 2,
                'id_variante' => 1,
                'id_compra' => 2,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 20,
                'reserva_anterior' => 30,
                'reserva_nueva' => 50,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-21 22:47:45',
                'updated_at' => '2026-09-21 22:47:45',
            ],
            [
                'id' => 3,
                'id_variante' => 1,
                'id_compra' => NULL,
                'id_usuario' => 1,
                'tipo' => 'transferencia_tienda',
                'cantidad' => 20,
                'reserva_anterior' => 50,
                'reserva_nueva' => 30,
                'stock_anterior' => 0,
                'stock_nuevo' => 20,
                'observacion' => 'Transferencia de bodega a tienda.',
                'created_at' => '2026-09-21 22:48:12',
                'updated_at' => '2026-09-21 22:48:12',
            ],
            [
                'id' => 4,
                'id_variante' => 2,
                'id_compra' => 3,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 10,
                'reserva_anterior' => 0,
                'reserva_nueva' => 10,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-21 23:03:43',
                'updated_at' => '2026-09-21 23:03:43',
            ],
            [
                'id' => 5,
                'id_variante' => 2,
                'id_compra' => 4,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 40,
                'reserva_anterior' => 10,
                'reserva_nueva' => 50,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-21 23:03:56',
                'updated_at' => '2026-09-21 23:03:56',
            ],
            [
                'id' => 6,
                'id_variante' => 2,
                'id_compra' => NULL,
                'id_usuario' => 1,
                'tipo' => 'transferencia_tienda',
                'cantidad' => 15,
                'reserva_anterior' => 50,
                'reserva_nueva' => 35,
                'stock_anterior' => 0,
                'stock_nuevo' => 15,
                'observacion' => 'Transferencia de bodega a tienda',
                'created_at' => '2026-09-22 09:51:14',
                'updated_at' => '2026-09-22 09:51:14',
            ],
            [
                'id' => 7,
                'id_variante' => 9,
                'id_compra' => 5,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 10,
                'reserva_anterior' => 0,
                'reserva_nueva' => 10,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-22 10:36:10',
                'updated_at' => '2026-09-22 10:36:10',
            ],
            [
                'id' => 8,
                'id_variante' => 9,
                'id_compra' => 6,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 20,
                'reserva_anterior' => 10,
                'reserva_nueva' => 30,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-22 10:37:49',
                'updated_at' => '2026-09-22 10:37:49',
            ],
            [
                'id' => 9,
                'id_variante' => 10,
                'id_compra' => 7,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 20,
                'reserva_anterior' => 0,
                'reserva_nueva' => 20,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-22 10:51:54',
                'updated_at' => '2026-09-22 10:51:54',
            ],
            [
                'id' => 10,
                'id_variante' => 11,
                'id_compra' => 8,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 30,
                'reserva_anterior' => 0,
                'reserva_nueva' => 30,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-22 21:54:56',
                'updated_at' => '2026-09-22 21:54:56',
            ],
            [
                'id' => 11,
                'id_variante' => 14,
                'id_compra' => 9,
                'id_usuario' => 1,
                'tipo' => 'compra_recibida',
                'cantidad' => 22,
                'reserva_anterior' => 0,
                'reserva_nueva' => 22,
                'stock_anterior' => 0,
                'stock_nuevo' => 0,
                'observacion' => 'Entrada a bodega por compra recibida.',
                'created_at' => '2026-09-23 09:08:47',
                'updated_at' => '2026-09-23 09:08:47',
            ],
            [
                'id' => 12,
                'id_variante' => 14,
                'id_compra' => NULL,
                'id_usuario' => 1,
                'tipo' => 'transferencia_tienda',
                'cantidad' => 15,
                'reserva_anterior' => 22,
                'reserva_nueva' => 7,
                'stock_anterior' => 0,
                'stock_nuevo' => 15,
                'observacion' => 'Transferencia de bodega a tienda.',
                'created_at' => '2026-09-23 09:09:39',
                'updated_at' => '2026-09-23 09:09:39',
            ],
        ];

        DB::table('movimiento_bodega')->upsert($data, ['id'], ['id_variante', 'id_compra', 'id_usuario', 'tipo', 'cantidad', 'reserva_anterior', 'reserva_nueva', 'stock_anterior', 'stock_nuevo', 'observacion', 'created_at', 'updated_at']);
    }

    protected function seedVenta(): void
    {
        $data = [
            [
                'id' => 1,
                'id_usuario' => 1,
                'fecha' => '2026-09-26 11:55:55',
                'total' => '68.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-26 11:55:55',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 2,
                'id_usuario' => 1,
                'fecha' => '2026-09-26 19:41:10',
                'total' => '19.80',
                'metodo_pago' => 'Transferencia Bancaria',
                'comprobante_pago' => 'comprobantes_pago/au1dEQeCtNhz0zxyMVhKO44LFzB1KbklQ5Q8BdQ8.jpg',
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-26 19:41:10',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 3,
                'id_usuario' => 1,
                'fecha' => '2026-09-26 22:36:31',
                'total' => '24.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => '7890-1234',
                'precio_envio' => '0.00',
                'estado' => 'Confirmada',
                'tipo_venta' => 'Envio',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => NULL,
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 4,
                'id_usuario' => 1,
                'fecha' => '2026-09-26 22:38:22',
                'total' => '26.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => '6895-8594',
                'precio_envio' => '3.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Envio',
                'observaciones' => NULL,
                'comprobante_paquete' => 'comprobantes_paquete/2026-09-26_VNT-00004_paquete.jpeg',
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-27 13:45:08',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 5,
                'id_usuario' => 1,
                'fecha' => '2026-09-27 13:57:42',
                'total' => '63.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-27 13:57:42',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 6,
                'id_usuario' => 1,
                'fecha' => '2026-09-27 14:03:45',
                'total' => '66.00',
                'metodo_pago' => 'Transferencia Bancaria',
                'comprobante_pago' => 'comprobantes_pago/VNT-00006_2026-09-27_comprobante_pago.jpeg',
                'telefono' => '7867-9670',
                'precio_envio' => '3.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Envio',
                'observaciones' => NULL,
                'comprobante_paquete' => 'comprobantes_paquete/VNT-00006_2026-09-27_paquete.jpeg',
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-27 14:11:34',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 31,
                'id_usuario' => 2,
                'fecha' => '2026-09-16 11:20:00',
                'total' => '19.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-16 11:20:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 32,
                'id_usuario' => 2,
                'fecha' => '2026-09-17 14:15:00',
                'total' => '41.00',
                'metodo_pago' => 'Transferencia Bancaria',
                'comprobante_pago' => NULL,
                'telefono' => '7744-8899',
                'precio_envio' => '3.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Envio',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-18 16:30:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 33,
                'id_usuario' => 2,
                'fecha' => '2026-09-19 10:00:00',
                'total' => '24.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-19 10:00:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 34,
                'id_usuario' => 2,
                'fecha' => '2026-09-22 15:45:00',
                'total' => '63.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-22 15:45:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 35,
                'id_usuario' => 2,
                'fecha' => '2026-09-24 09:30:00',
                'total' => '22.00',
                'metodo_pago' => 'Transferencia Bancaria',
                'comprobante_pago' => NULL,
                'telefono' => '7822-4411',
                'precio_envio' => '3.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Envio',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-25 14:00:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 36,
                'id_usuario' => 2,
                'fecha' => '2026-09-28 10:15:00',
                'total' => '38.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-28 10:15:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 37,
                'id_usuario' => 2,
                'fecha' => '2026-09-28 16:30:00',
                'total' => '27.00',
                'metodo_pago' => 'Transferencia Bancaria',
                'comprobante_pago' => NULL,
                'telefono' => '7855-1234',
                'precio_envio' => '3.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Envio',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-29 11:00:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 38,
                'id_usuario' => 2,
                'fecha' => '2026-09-30 14:00:00',
                'total' => '63.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-30 14:00:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 39,
                'id_usuario' => 2,
                'fecha' => '2026-10-01 16:20:00',
                'total' => '19.80',
                'metodo_pago' => 'Transferencia Bancaria',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-10-01 16:20:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 40,
                'id_usuario' => 1,
                'fecha' => '2026-09-29 11:30:00',
                'total' => '24.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-09-29 11:30:00',
                'fecha_cancelacion' => NULL,
            ],
            [
                'id' => 41,
                'id_usuario' => 2,
                'fecha' => '2026-10-05 14:00:00',
                'total' => '19.00',
                'metodo_pago' => 'Efectivo',
                'comprobante_pago' => NULL,
                'telefono' => NULL,
                'precio_envio' => '0.00',
                'estado' => 'Entregada',
                'tipo_venta' => 'Tienda',
                'observaciones' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
                'fecha_entrega' => '2026-10-05 14:00:00',
                'fecha_cancelacion' => NULL,
            ],
        ];

        DB::table('venta')->upsert($data, ['id'], ['id_usuario', 'fecha', 'total', 'metodo_pago', 'comprobante_pago', 'telefono', 'precio_envio', 'estado', 'tipo_venta', 'observaciones', 'comprobante_paquete', 'comprobante_devolucion', 'fecha_entrega', 'fecha_cancelacion']);
    }

    protected function seedSalida(): void
    {
        $data = [
            [
                'id' => 1,
                'id_variante' => 14,
                'id_usuario' => 1,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-26',
                'hora_salida' => '11:55:55',
                'fecha_entrega' => '2026-09-26',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '5.00',
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
                'descuento' => '0.00',
                'total' => '68.00',
                'costo_total_aplicado' => '30.00',
                'comision_aplicada' => '0.00',
                'observaciones' => 'Venta #1 (Costo extra: $5.00)',
                'estado' => 'Entregado',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-26 11:55:55',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 2,
                'id_variante' => 2,
                'id_usuario' => 1,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-26',
                'hora_salida' => '19:41:10',
                'fecha_entrega' => '2026-09-26',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '19.80',
                'subtotal' => '19.80',
                'descuento' => '0.00',
                'total' => '19.80',
                'costo_total_aplicado' => '8.40',
                'comision_aplicada' => '0.00',
                'observaciones' => 'Venta #2',
                'estado' => 'Entregado',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-26 19:41:10',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 3,
                'id_variante' => 1,
                'id_usuario' => 1,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-26',
                'hora_salida' => '22:35:00',
                'fecha_entrega' => '2026-09-26',
                'direccion' => 'Colonia San Benito #123, San Salvador',
                'precio_envio' => '0.00',
                'costo_extra' => '5.00',
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
                'descuento' => '0.00',
                'total' => '24.00',
                'costo_total_aplicado' => '8.00',
                'comision_aplicada' => '0.00',
                'observaciones' => 'Venta #3 (Costo extra: $5.00)',
                'estado' => 'Confirmada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-26 22:36:31',
                'telefono' => '7890-1234',
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 4,
                'id_variante' => 1,
                'id_usuario' => 1,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-26',
                'hora_salida' => '22:37:00',
                'fecha_entrega' => '2026-09-27',
                'direccion' => 'Calle al matazano (Ref: Frente a alcaldia)',
                'precio_envio' => '3.00',
                'costo_extra' => '4.00',
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
                'descuento' => '0.00',
                'total' => '23.00',
                'costo_total_aplicado' => '8.00',
                'comision_aplicada' => '0.00',
                'observaciones' => 'Venta #4 (Costo extra: $4.00)',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-26 22:38:22',
                'telefono' => '6895-8594',
                'comprobante_paquete' => 'comprobantes_paquete/2026-09-26_VNT-00004_paquete.jpeg',
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 5,
                'id_variante' => 14,
                'id_usuario' => 1,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-27',
                'hora_salida' => '13:57:42',
                'fecha_entrega' => '2026-09-27',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
                'descuento' => '0.00',
                'total' => '63.00',
                'costo_total_aplicado' => '30.00',
                'comision_aplicada' => '0.00',
                'observaciones' => 'Venta #5',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-27 13:57:42',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 6,
                'id_variante' => 14,
                'id_usuario' => 1,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-27',
                'hora_salida' => '14:02:00',
                'fecha_entrega' => '2026-09-27',
                'direccion' => 'San Julian',
                'precio_envio' => '3.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
                'descuento' => '0.00',
                'total' => '63.00',
                'costo_total_aplicado' => '30.00',
                'comision_aplicada' => '0.00',
                'observaciones' => 'Venta #6',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-27 14:03:45',
                'telefono' => '7867-9670',
                'comprobante_paquete' => 'comprobantes_paquete/VNT-00006_2026-09-27_paquete.jpeg',
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 31,
                'id_variante' => 1,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-16',
                'hora_salida' => '11:20:00',
                'fecha_entrega' => '2026-09-16',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
                'descuento' => '0.00',
                'total' => '19.00',
                'costo_total_aplicado' => '8.00',
                'comision_aplicada' => '3.00',
                'observaciones' => 'Venta #31',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-16 11:20:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 32,
                'id_variante' => 1,
                'id_usuario' => 2,
                'cantidad' => 2,
                'fecha_salida' => '2026-09-17',
                'hora_salida' => '14:15:00',
                'fecha_entrega' => '2026-09-18',
                'direccion' => 'Colonia Escalon, Pasaje 3 #45, San Salvador',
                'precio_envio' => '3.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '19.00',
                'subtotal' => '38.00',
                'descuento' => '0.00',
                'total' => '41.00',
                'costo_total_aplicado' => '16.00',
                'comision_aplicada' => '6.00',
                'observaciones' => 'Venta #32',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-17 14:15:00',
                'telefono' => '7744-8899',
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 33,
                'id_variante' => 10,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-19',
                'hora_salida' => '10:00:00',
                'fecha_entrega' => '2026-09-19',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '24.00',
                'subtotal' => '24.00',
                'descuento' => '0.00',
                'total' => '24.00',
                'costo_total_aplicado' => '10.00',
                'comision_aplicada' => '4.00',
                'observaciones' => 'Venta #33',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-19 10:00:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 34,
                'id_variante' => 14,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-22',
                'hora_salida' => '15:45:00',
                'fecha_entrega' => '2026-09-22',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
                'descuento' => '0.00',
                'total' => '63.00',
                'costo_total_aplicado' => '30.00',
                'comision_aplicada' => '3.00',
                'observaciones' => 'Venta #34',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-22 15:45:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 35,
                'id_variante' => 1,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-24',
                'hora_salida' => '09:30:00',
                'fecha_entrega' => '2026-09-25',
                'direccion' => 'Residencial San Antonio, Senda 2, Santa Tecla',
                'precio_envio' => '3.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
                'descuento' => '0.00',
                'total' => '22.00',
                'costo_total_aplicado' => '8.00',
                'comision_aplicada' => '3.00',
                'observaciones' => 'Venta #35',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-24 09:30:00',
                'telefono' => '7822-4411',
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 36,
                'id_variante' => 1,
                'id_usuario' => 2,
                'cantidad' => 2,
                'fecha_salida' => '2026-09-28',
                'hora_salida' => '10:15:00',
                'fecha_entrega' => '2026-09-28',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '19.00',
                'subtotal' => '38.00',
                'descuento' => '0.00',
                'total' => '38.00',
                'costo_total_aplicado' => '16.00',
                'comision_aplicada' => '6.00',
                'observaciones' => 'Venta #36',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-28 10:15:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 37,
                'id_variante' => 10,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-28',
                'hora_salida' => '16:30:00',
                'fecha_entrega' => '2026-09-29',
                'direccion' => 'Colonia Miramonte, Calle Principal #12, San Salvador',
                'precio_envio' => '3.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '24.00',
                'subtotal' => '24.00',
                'descuento' => '0.00',
                'total' => '27.00',
                'costo_total_aplicado' => '10.00',
                'comision_aplicada' => '4.00',
                'observaciones' => 'Venta #37',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-28 16:30:00',
                'telefono' => '7855-1234',
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 38,
                'id_variante' => 14,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-30',
                'hora_salida' => '14:00:00',
                'fecha_entrega' => '2026-09-30',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
                'descuento' => '0.00',
                'total' => '63.00',
                'costo_total_aplicado' => '30.00',
                'comision_aplicada' => '3.00',
                'observaciones' => 'Venta #38',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-30 14:00:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 39,
                'id_variante' => 2,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-10-01',
                'hora_salida' => '16:20:00',
                'fecha_entrega' => '2026-10-01',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '19.80',
                'subtotal' => '19.80',
                'descuento' => '0.00',
                'total' => '19.80',
                'costo_total_aplicado' => '8.40',
                'comision_aplicada' => '3.00',
                'observaciones' => 'Venta #39',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-10-01 16:20:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 40,
                'id_variante' => 10,
                'id_usuario' => 1,
                'cantidad' => 1,
                'fecha_salida' => '2026-09-29',
                'hora_salida' => '11:30:00',
                'fecha_entrega' => '2026-09-29',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '24.00',
                'subtotal' => '24.00',
                'descuento' => '0.00',
                'total' => '24.00',
                'costo_total_aplicado' => '10.00',
                'comision_aplicada' => '4.00',
                'observaciones' => 'Venta #40',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-09-29 11:30:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
            [
                'id' => 41,
                'id_variante' => 1,
                'id_usuario' => 2,
                'cantidad' => 1,
                'fecha_salida' => '2026-10-05',
                'hora_salida' => '14:00:00',
                'fecha_entrega' => '2026-10-05',
                'direccion' => 'Venta en mostrador / POS',
                'precio_envio' => '0.00',
                'costo_extra' => '0.00',
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
                'descuento' => '0.00',
                'total' => '19.00',
                'costo_total_aplicado' => '8.00',
                'comision_aplicada' => '3.00',
                'observaciones' => 'Venta #41',
                'estado' => 'Entregada',
                'fecha_cancelacion' => NULL,
                'created_at' => '2026-10-05 14:00:00',
                'telefono' => NULL,
                'comprobante_paquete' => NULL,
                'comprobante_devolucion' => NULL,
            ],
        ];

        DB::table('salida')->upsert($data, ['id'], ['id_variante', 'id_usuario', 'cantidad', 'fecha_salida', 'hora_salida', 'fecha_entrega', 'direccion', 'precio_envio', 'costo_extra', 'precio_unitario', 'subtotal', 'descuento', 'total', 'costo_total_aplicado', 'comision_aplicada', 'observaciones', 'estado', 'fecha_cancelacion', 'created_at', 'telefono', 'comprobante_paquete', 'comprobante_devolucion']);
    }

    protected function seedDetalleventa(): void
    {
        $data = [
            [
                'id' => 1,
                'id_venta' => 1,
                'id_variante' => 14,
                'cantidad' => 1,
                'precio_unitario' => '63.00',
                'subtotal' => '68.00',
            ],
            [
                'id' => 2,
                'id_venta' => 2,
                'id_variante' => 2,
                'cantidad' => 1,
                'precio_unitario' => '19.80',
                'subtotal' => '19.80',
            ],
            [
                'id' => 3,
                'id_venta' => 3,
                'id_variante' => 1,
                'cantidad' => 1,
                'precio_unitario' => '19.00',
                'subtotal' => '24.00',
            ],
            [
                'id' => 4,
                'id_venta' => 4,
                'id_variante' => 1,
                'cantidad' => 1,
                'precio_unitario' => '19.00',
                'subtotal' => '23.00',
            ],
            [
                'id' => 5,
                'id_venta' => 5,
                'id_variante' => 14,
                'cantidad' => 1,
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
            ],
            [
                'id' => 6,
                'id_venta' => 6,
                'id_variante' => 14,
                'cantidad' => 1,
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
            ],
            [
                'id' => 31,
                'id_venta' => 31,
                'id_variante' => 1,
                'cantidad' => 1,
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
            ],
            [
                'id' => 32,
                'id_venta' => 32,
                'id_variante' => 1,
                'cantidad' => 2,
                'precio_unitario' => '19.00',
                'subtotal' => '38.00',
            ],
            [
                'id' => 33,
                'id_venta' => 33,
                'id_variante' => 10,
                'cantidad' => 1,
                'precio_unitario' => '24.00',
                'subtotal' => '24.00',
            ],
            [
                'id' => 34,
                'id_venta' => 34,
                'id_variante' => 14,
                'cantidad' => 1,
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
            ],
            [
                'id' => 35,
                'id_venta' => 35,
                'id_variante' => 1,
                'cantidad' => 1,
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
            ],
            [
                'id' => 36,
                'id_venta' => 36,
                'id_variante' => 1,
                'cantidad' => 2,
                'precio_unitario' => '19.00',
                'subtotal' => '38.00',
            ],
            [
                'id' => 37,
                'id_venta' => 37,
                'id_variante' => 10,
                'cantidad' => 1,
                'precio_unitario' => '24.00',
                'subtotal' => '24.00',
            ],
            [
                'id' => 38,
                'id_venta' => 38,
                'id_variante' => 14,
                'cantidad' => 1,
                'precio_unitario' => '63.00',
                'subtotal' => '63.00',
            ],
            [
                'id' => 39,
                'id_venta' => 39,
                'id_variante' => 2,
                'cantidad' => 1,
                'precio_unitario' => '19.80',
                'subtotal' => '19.80',
            ],
            [
                'id' => 40,
                'id_venta' => 40,
                'id_variante' => 10,
                'cantidad' => 1,
                'precio_unitario' => '24.00',
                'subtotal' => '24.00',
            ],
            [
                'id' => 41,
                'id_venta' => 41,
                'id_variante' => 1,
                'cantidad' => 1,
                'precio_unitario' => '19.00',
                'subtotal' => '19.00',
            ],
        ];

        DB::table('detalleventa')->upsert($data, ['id'], ['id_venta', 'id_variante', 'cantidad', 'precio_unitario', 'subtotal']);
    }

    protected function seedComisionVendedor(): void
    {
        $data = [
            // --- Historial de Liquidaciones Semana 38 (14-20 Sep 2026) - Ana Plasma (PAGADAS) ---
            [
                'id' => 31,
                'id_vendedor' => 2,
                'id_salida' => 31,
                'concepto' => 'Venta #31 (1x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Blanca)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pagada',
                'metodo_pago' => 'Transferencia Bancaria',
                'referencia_pago' => 'TRANSF-BAC-78192',
                'comprobante_pago' => NULL,
                'notas' => 'Liquidación semanal corte #38.',
                'liquidado_por' => 1,
                'fecha_liquidacion' => '2026-09-21 16:00:00',
                'fecha_registro' => '2026-09-16 11:20:00',
            ],
            [
                'id' => 32,
                'id_vendedor' => 2,
                'id_salida' => 32,
                'concepto' => 'Venta #32 (2x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Blanca)',
                'monto' => '6.00',
                'porcentaje' => '3.00',
                'estado' => 'Pagada',
                'metodo_pago' => 'Transferencia Bancaria',
                'referencia_pago' => 'TRANSF-BAC-78192',
                'comprobante_pago' => NULL,
                'notas' => 'Liquidación semanal corte #38.',
                'liquidado_por' => 1,
                'fecha_liquidacion' => '2026-09-21 16:00:00',
                'fecha_registro' => '2026-09-17 14:15:00',
            ],
            [
                'id' => 33,
                'id_vendedor' => 2,
                'id_salida' => 33,
                'concepto' => 'Venta #33 (1x CAMARA FOCO Giro 360° - Dos focos)',
                'monto' => '4.00',
                'porcentaje' => '4.00',
                'estado' => 'Pagada',
                'metodo_pago' => 'Transferencia Bancaria',
                'referencia_pago' => 'TRANSF-BAC-78192',
                'comprobante_pago' => NULL,
                'notas' => 'Liquidación semanal corte #38.',
                'liquidado_por' => 1,
                'fecha_liquidacion' => '2026-09-21 16:00:00',
                'fecha_registro' => '2026-09-19 10:00:00',
            ],

            // --- Historial de Liquidaciones Semana 39 (21-27 Sep 2026) - Ana Plasma ---
            [
                'id' => 34,
                'id_vendedor' => 2,
                'id_salida' => 34,
                'concepto' => 'Venta #34 (1x LUCES TRASERAS CON EFECTO 3D - Amarilla)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pagada',
                'metodo_pago' => 'Efectivo',
                'referencia_pago' => 'REC-00194',
                'comprobante_pago' => NULL,
                'notas' => 'Liquidación semanal corte #39.',
                'liquidado_por' => 1,
                'fecha_liquidacion' => '2026-09-28 17:30:00',
                'fecha_registro' => '2026-09-22 15:45:00',
            ],
            [
                'id' => 35,
                'id_vendedor' => 2,
                'id_salida' => 35,
                'concepto' => 'Venta #35 (1x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Blanca)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión registrada tras entrega exitosa del envío.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-24 09:30:00',
            ],

            // --- Semana 40 (28 Sep - 04 Oct 2026) - SEMANA ANTERIOR (PENDIENTES Y DESBLOQUEADAS POR GARANTÍA EXPIRADA) ---
            [
                'id' => 36,
                'id_vendedor' => 2,
                'id_salida' => 36,
                'concepto' => 'Venta #36 (2x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Blanca)',
                'monto' => '6.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión liquidable corte semana anterior.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-28 10:15:00',
            ],
            [
                'id' => 37,
                'id_vendedor' => 2,
                'id_salida' => 37,
                'concepto' => 'Venta #37 (1x CAMARA FOCO Giro 360° - Dos focos)',
                'monto' => '4.00',
                'porcentaje' => '4.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión registrada tras entrega exitosa del envío.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-28 16:30:00',
            ],
            [
                'id' => 38,
                'id_vendedor' => 2,
                'id_salida' => 38,
                'concepto' => 'Venta #38 (1x LUCES TRASERAS CON EFECTO 3D - Amarilla)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión liquidable corte semana anterior.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-30 14:00:00',
            ],
            [
                'id' => 39,
                'id_vendedor' => 2,
                'id_salida' => 39,
                'concepto' => 'Venta #39 (1x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Amarrilla)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión liquidable corte semana anterior.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-10-01 16:20:00',
            ],
            [
                'id' => 40,
                'id_vendedor' => 1,
                'id_salida' => 40,
                'concepto' => 'Venta #40 (1x CAMARA FOCO Giro 360° - Dos focos)',
                'monto' => '4.00',
                'porcentaje' => '4.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión liquidable corte semana anterior.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-29 11:30:00',
            ],

            // --- Semana 41 (05-11 Oct 2026) - SEMANA ACTUAL (PENDIENTE PERO EN GARANTÍA ACTIVA / BLOQUEADA) ---
            [
                'id' => 41,
                'id_vendedor' => 2,
                'id_salida' => 41,
                'concepto' => 'Venta #41 (1x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Blanca)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión en período de garantía de devolución.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-10-05 14:00:00',
            ],

            // --- Comisiones asociadas a las salidas iniciales 1, 2, 4, 5, 6 ---
            [
                'id' => 42,
                'id_vendedor' => 1,
                'id_salida' => 1,
                'concepto' => 'Venta #1 (1x LUCES TRASERAS CON EFECTO 3D - Amarilla)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pagada',
                'metodo_pago' => 'Efectivo',
                'referencia_pago' => 'REC-00101',
                'comprobante_pago' => NULL,
                'notas' => 'Liquidación procesada.',
                'liquidado_por' => 1,
                'fecha_liquidacion' => '2026-09-28 10:00:00',
                'fecha_registro' => '2026-09-26 11:55:55',
            ],
            [
                'id' => 43,
                'id_vendedor' => 1,
                'id_salida' => 2,
                'concepto' => 'Venta #2 (1x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Amarrilla)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pagada',
                'metodo_pago' => 'Efectivo',
                'referencia_pago' => 'REC-00101',
                'comprobante_pago' => NULL,
                'notas' => 'Liquidación procesada.',
                'liquidado_por' => 1,
                'fecha_liquidacion' => '2026-09-28 10:00:00',
                'fecha_registro' => '2026-09-26 19:41:10',
            ],
            [
                'id' => 44,
                'id_vendedor' => 1,
                'id_salida' => 4,
                'concepto' => 'Venta #4 (1x ALOGENAS ESPLORADORA FUERTE ILUMINACIÓN CON SWITCH. - Luz Blanca)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión registrada tras entrega exitosa del envío.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-26 22:38:22',
            ],
            [
                'id' => 45,
                'id_vendedor' => 1,
                'id_salida' => 5,
                'concepto' => 'Venta #5 (1x LUCES TRASERAS CON EFECTO 3D - Amarilla)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión pendiente de liquidar.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-27 13:57:42',
            ],
            [
                'id' => 46,
                'id_vendedor' => 1,
                'id_salida' => 6,
                'concepto' => 'Venta #6 (1x LUCES TRASERAS CON EFECTO 3D - Amarilla)',
                'monto' => '3.00',
                'porcentaje' => '3.00',
                'estado' => 'Pendiente',
                'metodo_pago' => NULL,
                'referencia_pago' => NULL,
                'comprobante_pago' => NULL,
                'notas' => 'Comisión registrada tras entrega exitosa del envío.',
                'liquidado_por' => NULL,
                'fecha_liquidacion' => NULL,
                'fecha_registro' => '2026-09-27 14:03:45',
            ],
        ];

        DB::table('comision_vendedor')->upsert($data, ['id'], [
            'id_vendedor',
            'id_salida',
            'concepto',
            'monto',
            'porcentaje',
            'estado',
            'metodo_pago',
            'referencia_pago',
            'comprobante_pago',
            'notas',
            'liquidado_por',
            'fecha_liquidacion',
            'fecha_registro',
        ]);
    }

    protected function resetPostgresSequences(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        $tables = [
            'usuario',
            'proveedors',
            'categoria',
            'atributo',
            'producto',
            'catalogos',
            'productoatributo',
            'variante',
            'variante_imagen',
            'variantevalor',
            'compra',
            'compra_detalle',
            'movimiento_bodega',
            'venta',
            'salida',
            'detalleventa',
            'comision_vendedor',
            'devoluciones',
            'devolucion_detalles',
        ];

        foreach ($tables as $table) {
            $seq = DB::selectOne("SELECT pg_get_serial_sequence('{$table}', 'id') AS seq");
            if ($seq && $seq->seq) {
                DB::statement("SELECT setval('{$seq->seq}', COALESCE((SELECT MAX(id) FROM \"{$table}\"), 1))");
            }
        }
    }
}